# Generated by Django 4.2.5 on 2023-10-23 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0008_rename_ammenityslotend_amenityslot_amenityslotend_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='userProvider',
            field=models.CharField(default=''),
        ),
    ]
