# Generated by Django 4.2.5 on 2023-10-23 23:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0009_request_userprovider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bookingId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
