# Generated by Django 4.2.5 on 2023-10-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0012_amenity_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='dateSlot',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='timeStart',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
