# Generated by Django 4.2.5 on 2023-12-08 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0014_teamrequest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamRequest',
        ),
    ]
