# Generated by Django 4.2.5 on 2023-10-21 12:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0002_alter_request_teamid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='teamId',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
