# Generated by Django 4.2.5 on 2023-10-25 11:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookingApp', '0011_remove_booking_individuals_booking_individuals'),
    ]

    operations = [
        migrations.AddField(
            model_name='amenity',
            name='capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
